# Generated by Django 3.2.8 on 2021-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_tada_travel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tada',
            name='instruments_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tada',
            name='lunch_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tada',
            name='travel_cost',
            field=models.IntegerField(default=0),
        ),
    ]
